docs/xff-proposal.md
- istio-manager API proposal
https://github.com/kyma-project/istio/issues/11
=> istio-manager API proposal

operator/api/v1alpha1/istio_types.go, operator/config/crd/bases/operator.kyma-project.io_istios.yaml, operator/config/samples/operator_v1alpha1_istio.yaml, operator/controllers/istio_manifest_resolver.go
Remove the field as it won't be used for now
=> Remove "ReleaseName" from CRD

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/dependabot.yml, .github/pull-request-template.md
Add Dependabot config and GitHub templates
=> Add Dependabot config

charts/istio-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_istios.operator.kyma-project.io.yaml, operator/api/v1alpha1/istio_structs.go, operator/api/v1alpha1/istio_types.go, operator/config/crd/bases/operator.kyma-project.io_istios.yaml
- Updates to the CR descriptions
https://github.com/kyma-project/kyma/issues/16042
=> Update CR descriptions

operator/api/v1alpha1/istio_merge.go, operator/api/v1alpha1/istio_merge_test.go
=> Add more checks for nil

README.md, docs/istio-whitelogo-bluebackground-framed.svg
- Update Istio logo to local resource
=> Update istio logo

operator/api/v1alpha1/istio_types.go, operator/config/crd/bases/operator.kyma-project.io_istios.yaml, operator/controllers/istio_controller.go
- Change status "Reconciling" to "Processing". The status name is [required by module-manager](https://github.com/kyma-project/template-operator#steps-api-definition)
=> Change status "Reconciling" to "Processing"

operator/config/manager/manager.yaml, operator/controllers/istio_controller.go, operator/controllers/istio_types.go, operator/internal/reconciliations/istio/client.go, operator/internal/reconciliations/istio/installation.go, operator/internal/reconciliations/proxy/sidecars.go, operator/pkg/lib/sidecars/pods/get.go, operator/pkg/lib/sidecars/restart/restart_test.go, operator/pkg/lib/sidecars/restart/rollout_action.go, operator/pkg/lib/sidecars/test/cases.go
- ...
- ...
- ...
- https://github.com/kyma-project/istio/issues/66
=> Add proxy sidecars reconciliation

operator/config/rbac/role.yaml
- Add permissions for StatefulSets to controller-manager, because the proxy reset requires them
- https://github.com/kyma-project/istio/issues/66
=> Add StatefulSets permission to controller-manager

operator/internal/reconciliations/proxy/sidecars.go
=> Fix wrong usage of structured logging

operator/pkg/lib/sidecars/restart/rollout_action.go
=> Use patch instead of an update in sidecar rollout action

operator/README.md
=> Review the operator README

operator/manifests/default-istio-operator-cluster.yaml, operator/manifests/default-istio-operator-k3d.yaml
- Apply changes to default istio operator introduced in https://github.com/kyma-project/kyma/pull/16848
- https://github.com/kyma-project/kyma/pull/16848
=> Update Istio default operator manifests HPA to autoscaling/v2

operator/internal/reconciliations/istio/client.go
-  Use the same deletion propagation as the current reconciler implementation
=> Change istio-system deletion propagation

controllers/istio_controller.go, internal/reconciliations/istio/installation.go, internal/reconciliations/istio/installation_test.go, pkg/lib/sidecars/pods/get.go, pkg/lib/sidecars/pods/get_test.go, pkg/lib/sidecars/remove/remove.go, pkg/lib/sidecars/remove/remove_test.go, pkg/lib/sidecars/test/helpers/helpers.go
- Trigger restart of injected pods after uninstallation of Istio
- https://github.com/kyma-project/istio/issues/107
=> Remove sidecar after Istio uninstallation

hack/ci/Makefile
=> Push module template to artifacts

Dockerfile
- Change `golang:1.20` base to `eu.gcr.io/kyma-project/external/golang:1.20.2-alpine3.17`
=> Use kyma-project image version for Istio module

controllers/istio_controller.go, go.mod, go.sum
- Bump Istio client-go to 1.17.x
- https://istio.io/latest/news/releases/1.17.x/announcing-1.17/
https://github.com/kyma-project/istio/issues/105
=> Bump Istio client-go to 1.17.x

tests/integration/scripts/code-coverage-guard.sh
=> Add code coverage guard

go.mod, go.sum, internal/reconciliations/istio/configuration.go, internal/reconciliations/istio/installation_test.go
=> Istio version checking

docs/technical-design.md
=> Add info about Istio upgrade version checking

.github/ISSUE_TEMPLATE/adr.md
=> Create adr.md issue template

manifests/controlled_resources_list.yaml
- Add comment with link to Istio resources list
=> Add reference to Istio CRDs in controlled_resources_list

hack/local/istio/Makefile
- Add `"operator.kyma-project.io/use-local-template": "true"` label, required after https://github.com/kyma-project/lifecycle-manager/pull/496
=> Fix istio-manager-verify pipeline

.github/ISSUE_TEMPLATE/adr.md, .github/ISSUE_TEMPLATE/feature_request.md
Add information that codeowner has to verify code coverage for newly added feature.
=> Update issue templates

config/samples/operator_v1alpha1_istio.yaml
The Istio sample is used by lifecycle manager for default installation. It should not have any configuration by default.
- Clean up Istio sample for default installation
=> Clean up istio sample

manifests/istio-operator-template.yaml
- Update AWS LB on Istio GW connection timeout settings via annotation
https://github.com/kyma-project/kyma/issues/17496
=> Update AWS LB on Istio GW connection timeout settings via annotation

Makefile, config/manager/manager.yaml, tests/integration/.gitignore, tests/integration/main_test.go, tests/integration/test_report.go
- Add html reporter for Istio tests
=> Add html reporter for Istio module

config/default/kustomization.yaml, config/manager/manager.yaml, config/rbac/kustomization.yaml
The unsigned image `gcr.io/kubebuilder/kube-rbac-proxy` currently blocks the deployment. More details can be found in [this comment](https://github.com/kyma-project/istio/issues/168#issuecomment-1596856137).
- Remove metrics auth to match the configuration in other modules
- https://github.com/kyma-project/istio/issues/168
=> Remove metrics auth

sec-scanners-config.yaml
- Add config for security scanner
- https://github.com/kyma-project/istio/issues/186
=> Add security scanner config

docs/contributor/04-10-technical-design.md
- correct the wrong diagram name in the link
- https://github.com/kyma-project/istio/pull/170/files
=> Fix a link

.github/workflows/create-release.yaml, Makefile, docs/release-notes/0.1.0.md, docs/release-notes/template.md, scripts/create_changelog.sh, scripts/create_draft_release.sh, scripts/publish_assets.sh, scripts/publish_release.sh
- Add "Create release" GitHub action
=> Add release GitHub action

.github/workflows/create-release.yaml
- Add space in `create-release.yaml`
=> Fix indentation in create-release.yaml

.github/workflows/lint.yaml
- Add commit pin to lint workflow setup-go action due to error thrown on create release workflow ( https://github.com/kolodziejczak/istio/actions/runs/5462961056 )
=> Lint workflow pin

Makefile, tests/integration/hooks.go
- Increase test timeout
- Improve logging of Istio CR force removal hook to better investigate integration test issues on GCP if they occur again
=> Improve integration test reliability

scripts/create_draft_release.sh
- Allow to create releases only with semantic versioned tags
=> Disallow non semantic versioned tags

.github/workflows/create-release.yaml
- Use different GitHub action that waits on checks based on `context` instead of check name
=> Wait for status instead of check on release job

.github/dependabot.yml
- Fix directory configuration of existing configuration
- Add config for GitHub Actions
=> Update dependabot Docker config

docs/release-notes/0.2.0.md
=> Create release notes for 0.2.0

.github/dependabot.yml
- Add dependabot config for release branch
=> Update dependabot.yml for release 0.2

.github/workflows/create-release.yaml, .github/workflows/pull-integration.yaml, main.go
- Check status of waiting for build GitHub action
=> Check that builds end in success

.github/workflows/pull-request.yaml
- Run pull request workflow on Pull requests to release branches
=> Run PR workflow on release branches

.github/workflows/main-cache.yaml
=> Fix build-cache job config

cmd/istio-install/main.go
- Fix logging so all errors are visible in the manager log
=> Fix Istio install error logging in child process

controllers/istio_controller.go, docs/release-notes/0.2.1.md, go.mod, go.sum, sec-scanners-config.yaml
- Bump istio version to 1.18.1
=> [release/0.2] Bump istio to 1.18.1

controllers/istio_controller.go, docs/release-notes/0.2.1.md, go.mod, go.sum, sec-scanners-config.yaml
=> Bump istio to 1.18.1

docs/release-notes/1.0.0.md, go.mod, go.sum, internal/reconciliations/istio/installation.go, internal/webhooks/webhooks.go, internal/webhooks/webhooks_test.go
- Cleanup MutatingWebhook on failed installation
- https://github.com/kyma-project/istio/issues/154
=> Cleanup MWC on installation failure

manifests/istio-operator-template-light.yaml, manifests/istio-operator-template.yaml
- Enable configuration for dynamic envoy bootstrap in Istio module
- EnvoyFilter can be left as follow up for now, as it will be created by reconciler before we rollout the module to live clusters
- https://github.com/orgs/kyma-project/projects/27/views/1?pane=issue&itemId=33556019
=> Enable bootstrap XDS agent in Istio module

config/default/kustomization.yaml, config/resourcequota/kustomization.yaml, config/resourcequota/resource_quota_count.yaml, docs/contributor/04-10-technical-design.md, docs/contributor/04-20-xff-proposal.md, tests/integration/features/istio/evaluation/istio_installation_demo.feature, tests/integration/features/istio/production/configuration.feature, tests/integration/features/istio/production/istio_installation.feature, tests/integration/scenario.go, tests/integration/steps/istio_cr.go, tests/integration/steps/resource.go
- Revert ResourceQuota due to some issues
=> Revert ResourceQuota due to some issues

controllers/istio_controller.go, controllers/istio_controller_test.go, docs/contributor/04-10-technical-design.md, docs/contributor/04-20-xff-proposal.md, tests/integration/features/istio/production/istio_installation.feature, tests/integration/hooks.go, tests/integration/steps/istio_cr.go, tests/integration/testcontext/context.go
- We do not reconcile newer Istio CRs, only the oldest one
https://github.com/kyma-project/istio/issues/172
=> We do not reconcile newer Istio CRs, only the oldest one

controllers/istio_controller.go, docs/release-notes/1.0.0.md, go.mod, go.sum, sec-scanners-config.yaml
- Update istio version to 1.18.2
=> Update istio version to 1.18.2

Makefile, hack/ci/Makefile
Use regular channel for CI builds.
- Set default release channel to fast, since alpha channel is not a defined release channel
- Set release channel for CI builds to regular
- https://github.com/kyma-project/istio/issues/282
=> Generate Istio module template for regular release channel

.github/workflows/pull-request.yaml
=> Coverage guard run on PR

config/default/kustomization.yaml, config/ui-extensions/istios/details, config/ui-extensions/istios/form, config/ui-extensions/istios/general, config/ui-extensions/istios/kustomization.yaml, config/ui-extensions/istios/list, config/ui-extensions/istios/translations, config/ui-extensions/kustomization.yaml, tests/integration/pkg/manifestprocessor/processor.go, tests/integration/steps/operator.go
- Adds busola UI extension for istio operator
https://github.com/kyma-project/istio/issues/284
=> Busola UI extension for Istio operator spec

.github/actions/slack-notification-failed-workflow/action.yaml, .github/actions/upgrade-integration-test/action.yaml, .github/workflows/main-integration.yaml, .github/workflows/pull-integration.yaml, tests/integration/main_test.go
=> Fix pipelines

config/ui-extensions/istios/translations
=> Fix busola UI typos

sec-scanners-config.yaml
=> Bump istio manager img in security scanner

config/ui-extensions/istios/details, config/ui-extensions/istios/list
- Add status badge error description to Istio UI extension
=> Add status badge error description to Istio UI extension

hack/ci/gardener-perf-test.sh
- Fix perf tests script running nightly Istio CR in kyma-system
=> Fix perf tests script running nightly Istio CR in kyma-system

sec-scanners-config.yaml
=> Bump img for security scans

Makefile, config/ui-extensions/istios/details, config/ui-extensions/istios/list
=> Fix error badge

sec-scanners-config.yaml
- Update img for security scans
=> Update img for sec scanner

.github/dependabot.yml
- Update Dependabot config, because the release branch is not correct and add new group for k8s dependencies
=> Update release branch in dependabot config and add k8s dependency group

sec-scanners-config.yaml
- Exclude test files from sec scans
=> Exclude test files from sec scans

config/ui-extensions/istios/form
- Add `required: false` to ensure that UI does not render `*`
=> Update UI making all configuration parts not required

sec-scanners-config.yaml
=> Update security scanner img

tests/integration/features/istio/production/main-suite/istio_resources.feature, tests/integration/scenario.go, tests/integration/steps/resource.go
- Add check that Istio resources are removed on Istio CR deletion
=> Uninstallation of istio resources test

tests/integration/features/istio/production/main-suite/istio_installation.feature, tests/integration/hooks.go, tests/integration/steps/resource.go
- Add test to verify manual deleted resources are recreated on reconciliation
- Add additional logging for debugging of flaky test
=> Add test to verify reconciliation of manually deleted resources

sec-scanners-config.yaml
- Bump image for security scanner
=> Bump sec scanner img

controllers/istio_controller.go, controllers/istio_controller_test.go, docs/user/02-operation-guides/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md, internal/reconciliations/istio/installation.go, internal/reconciliations/istio/installation_test.go, tests/integration/features/istio/production/main-suite/istio_installation.feature
- Added more context to warning information
- Adapt troubleshooting guide
=> Update Istio CR warning descriptions

.github/dependabot.yml
- Update release branch in Dependabot configuration
=> Update release branch in Dependabot configuration

sec-scanners-config.yaml
- Update security scanner config
=> Update security scanner config

tests/integration/features/istio/production/main-suite/istio_connection.feature, tests/integration/scenario.go, tests/integration/steps/deployment.go, tests/integration/steps/istio.go, tests/integration/steps/nginx.go, tests/integration/steps/nginx_config_template.yaml, tests/integration/steps/resource.go, tests/integration/steps/validation_requests.go
- Add integration test to verify connection between namespaces is working
=> Add Integration test to verify access between namespaces

Makefile, tests/integration/features/istio/production/main-suite/istio_connection.feature, tests/integration/main_test.go, tests/integration/scenario.go, tests/integration/steps/validation_requests.go, tests/integration/testsupport/http_response_asserter.go
=> Add integration test to verify default strict PeerAuthentication

tests/integration/features/istio/production/upgrade-suite/istio_upgrade.feature, tests/integration/scenario.go, tests/integration/steps/istio_cr.go
- Use the Update timestamp of status subresource to verify a reconciliation started, since there is no other stateless information available
=> Update upgrade integration test to avoid flakiness

sec-scanners-config.yaml
=> Update sec scanner image

internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.yaml
- Use boolean instead of string in envoy filter
**References**
- https://github.com/kyma-project/kyma/issues/18124#issuecomment-1719362297
=> Use boolean instead of string in envoy filter

sec-scanners-config.yaml
=> Update sec scanner

tests/integration/features/istio/production/main-suite/istio_resources.feature
- Make sure uninstall removes `kyma-gateway`
=> Make sure uninstall removes kyma-gateway

sec-scanners-config.yaml
=> update sec scanner img

sec-scanners-config.yaml
=> updace sec scanner

internal/reconciliations/istio_resources/envoy_filter_allow_partial_referer.yaml
- Cherry-pick https://github.com/kyma-project/istio/commit/262bf0407622da492b9c59a00f51ee7acbdcd198
=> Use boolean instead of string in envoy filter (#389)

Makefile, README.md, config/manager/manager.yaml
- Remove kyma-system namespace from config
- Create make target for creating kyma-system namespace
=> Istio module manifests should not deploy kyma-system

.github/workflows/vulnerabilities-check.yaml
- To avoid blocking PRs and releases, we should not run vulnerability check on PRs
=> Remove vulnerability check from PRs

.github/workflows/vulnerabilities-check.yaml, go.mod
=> Update go version

.github/dependabot.yml
- Ignore Istio dependencies in dependabot, since we never use the created PRs and have a different notification for new Istio releases.
=> Ignore istio dependencies in dependabot config

hack/managed-kyma-migration/migrate.sh, hack/managed-kyma-migration/migration-testing/migrate-local-moduletemplate.sh, hack/managed-kyma-migration/migration-testing/module-template-migration-test-fast.yaml, hack/managed-kyma-migration/migration-testing/revert-local-moduletemplate.sh, hack/managed-kyma-migration/moduletemplate-istio-fast-channel.yaml, hack/managed-kyma-migration/moduletemplate-istio-regular-channel.yaml, hack/managed-kyma-migration/post-enable-module.sh, hack/managed-kyma-migration/readme.md, hack/managed-kyma-migration/rename-to-default.sh
- Update managed kyma migration script and readme
=> Managed Kyma Migration Update

tests/integration/scripts/deploy-latest-release-to-cluster.sh
- Fix getting latest release logic
=> Fix upgrade test tags

.github/workflows/main-integration.yaml
=> Exclude main

Makefile, README.md
- Include istio-injection label when creating kyma-system ns
=> Include istio-injection label when creating kyma-system ns

Dockerfile
- Go version 1.21.5
- Alpine image 3.19
=> Bump Go version to 1.21.5 and use newer alpine image

docs/user/00-10-overview-istio-controller.md
- Add more details to the XFF header documentation
- Add TLS termination documentation
=> Update XFF header documentation

.github/dependabot.yml
- The Dependabot target branch was not updated during the release
=> Update Dependabot release target branch

CODE_OF_CONDUCT.md, CONTRIBUTING.md, NOTICE.md, README.md, SECURITY.md
- Add missing files from the [template-repository](https://github.com/kyma-project/template-repository)
=> Add missing files

tests/performance/Makefile
- Don't log k6 output, only html report
=> Make k6 logs quiet

tests/performance/Makefile
- Add 2 second sleep waiting for summary generation
=> Add sleep to Istio performance test

tests/ui/support/navigation.js
=> Fix UI test

sec-scanners-config.yaml
- Security scanner config update
=> Security scanner config update

README.md, hack/managed-kyma-migration/readme.md
=> Fix md links

.github/dependabot.yml
- Fix dependabot config for release-1.3
=> Fix dependabot config for release-1.3

.github/workflows/create-release.yaml, main.go
- Check if release tag is applied to sec-scanner config
=> Make sure security scanner configuration is updated before release

.github/actions/wait-for-job-succeed-or-fail/action.yaml, .github/workflows/pull-integration-gardener.yaml, main.go
=> Fix PR number env

.github/actions/wait-for-job-succeed-or-fail/action.yaml, .github/workflows/pull-integration-gardener.yaml
- Cp a0ad780b83c3c713012331ba7e2924573b9f44f7
=> Cherrypick a0ad780b83c3c713012331ba7e2924573b9f44f7

docs/user/00-10-overview-istio-controller.md, docs/user/00-20-overview-service-mesh.md, docs/user/operation-guides/02-20-enable-sidecar-injection.md, docs/user/operation-guides/02-30-enable-istio-access-logs.md, docs/user/tutorials/01-00-x-forwarded-for-header.md
- Update the syntax used for the notes
#18552
=> Update the notes' style

.github/workflows/pull-integration-gardener.yaml
- Ignore sec-scanners-config.yaml for PR Integration Gardener workflow
=> Ignore sec-scanners-config.yaml for PR Integration Gardener workflow

sec-scanners-config.yaml
- Update istio-manager version for security scanners
=> Update istio-manager version for security scanners

docs/release-notes/1.4.0.md
/area documentation
/kind feature
/cc @nataliasitko 
Follow-up for #564 
#548
=> Add release notes for consistent labeling

manifests/controlled_resources_list.yaml
- Remove kyma-gateway from controlled resources list
https://github.com/kyma-project/istio/issues/466
=> Remove kyma-gateway from controlled resources list

.gitignore, config/ui-extensions/istios/details
- Add conditions to the UI
- Hide empty panels in Istio CR UI
- Reorganisation of the Istio CR UI so that it looks similar to other modules
=> Add conditions to Istio CR UI

.github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test/action.yaml, .github/actions/upgrade-integration-test/action.yaml, .github/workflows/main-integration.yaml, .github/workflows/performance-test.yaml, .github/workflows/pull-integration-gardener.yaml, .github/workflows/ui-tests.yaml, config/ui-extensions/istios/details
- Update actions, because PRs https://github.com/kyma-project/istio/pull/557 and https://github.com/kyma-project/istio/pull/556 doesn't run test successfully, because no manager is build
- Simplify Istio CR details UI
=> Update action version and simplify istio CR details UI

.github/ISSUE_TEMPLATE/feature_request.md
- Update DoD to include new item about Istio operator changes
=> Update DoD to include new item about Istio operator changes

internal/resources/apply.go
- Retrigger post main pipelines
=> Retrigger post pipelines

sec-scanners-config.yaml
- Update manager image in sec-scanners-config
=> Update manager image in sec-scanners-config

docs/contributor/04-10-technical-design.md, docs/release-notes/1.4.0.md, docs/user/00-10-overview-istio-controller.md, docs/user/04-00-istio-custom-resource.md
- Update the docs
- Add release notes
#613
=> Update the docs related to Warning state on duplicate Istio CRs

sec-scanners-config.yaml
- Add rc-tag for Release 1.3.1
=> Add rc-tag for Release 1.3.1

.github/ISSUE_TEMPLATE/istio_update.md, sec-scanners-config.yaml
- Add Istio Update issue template
- Remove rc-tag from sec-scanners-config.yaml
=> Add Istio Update issue template

docs/contributor/04-10-technical-design.md, docs/release-notes/1.4.0.md, docs/user/00-50-resource-configuration.md, docs/user/troubleshooting/03-50-recovering-from-unintentional-istio-removal.md, hack/managed-kyma-migration/readme.md
- Use 'in a cluster' instead of 'on a cluster'
https://github.com/kyma-project/kyma/issues/18581
=> Use 'in a cluster' instead of 'on a cluster'

.github/ISSUE_TEMPLATE/istio_update.md
- Fix a link that appears as broken in Markdown Link Checker
=> Fix a broken link

docs/user/tutorials/01-10-external-authorization-provider.md
- user tutorial with a custom external authorizer
#623
=> Add an user tutorial about setting up an external authorizer

tests/ui/cypress.config.js, tests/ui/scripts/k3d-ci-kyma-dashboard-integration.sh, tests/ui/support/buttons.js, tests/ui/support/filter.js, tests/ui/support/index.js, tests/ui/support/lists.js, tests/ui/support/login.js, tests/ui/support/navigation.js, tests/ui/support/views/namespace.js, tests/ui/support/views/service.js, tests/ui/tests/authorization-policies/test-authorization-policies.spec.js, tests/ui/tests/destination-rules/test-destination-rules.spec.js, tests/ui/tests/gateway/test-gateways.spec.js, tests/ui/tests/istio/test-virtual-services.spec.js, tests/ui/tests/service-entries/test-service-entries.spec.js, tests/ui/tests/sidecars/test-sidecars.spec.js
- Update UI tests to work with latest Busola version
=> Update UI tests to work with latest Busola version

sec-scanners-config.yaml
- Update security scanners config
=> Update security scanners config

.github/workflows/main-integration.yaml, .github/workflows/performance-test.yaml, .github/workflows/pull-integration-gardener.yaml, hack/ci/provision-gardener.sh
=> Fix gardener provisioning

hack/ci/provision-gardener.sh
- Add parameter to gardener provisioning command
=> Add parameter to gardener provisioning command

api/v1alpha2/conditions.go, api/v1alpha2/istio_types.go, controllers/istio_controller.go, controllers/istio_controller_test.go, tests/integration/features/istio/production/main-suite/istio_installation.feature, tests/integration/steps/istio_cr.go
As we need to make sure that the condition status is updated according to https://github.com/kyma-project/istio/issues/467, we introduce `Unknown` condition
- Add condition `Unknown` for `Ready` type
=> Add unknown condition

docs/user/_sidebar.md, docs/user/operation-guides/02-30-enable-istio-access-logs.md, docs/user/tutorials/01-00-x-forwarded-for-header.md, docs/user/tutorials/01-10-external-authorization-provider.md, docs/user/tutorials/README.md
- Add the External Authorizer tutorial to the sidebar
=> Add a tutorial to the sidebar

.github/workflows/main-integration.yaml, .github/workflows/performance-test.yaml, .github/workflows/pull-integration-gardener.yaml
(cherry picked from commit 9342adfc16c6382c1253f3ec2fa96dd53b533917)
- Cherry pick from main with fix for gardener provisioning
=> Fix gardener provisioning (#656)

hack/ci/provision-gardener.sh
(cherry picked from commit 015c56a0485132828161371f0d24aa857425cc14)
- Second part of cherry picking from main with the fix for gardener provisioning
=> Add parameter to gardener prov command (#657)

.github/workflows/ui-tests.yaml, go.mod, pkg/lib/sidecars/test/helpers/helpers.go
=> go 1.22 update

config/manager/manager.yaml, docs/release-notes/1.4.1.md, sec-scanners-config.yaml
- Cherry-pick https://github.com/kyma-project/istio/pull/684
- Update security scanners config
=> Update managers metrics address

docs/contributor/04-10-technical-design.md
- Fixed links to sections in Technical Design
=> Fix links to sections in Technical Design

docs/user/troubleshooting/03-00-istio-basic-diagnostics.md, docs/user/troubleshooting/first-troubleshooting-guide.md
- Add first version of the Istio troubleshooting guide
=> Istio troubleshooting guide

tests/integration/features/istio/production/main-suite/istio_observability.feature
- Wait for istio to get Ready in observability tests
=> Wait for istio to get Ready

docs/user/operation-guides/02-30-enable-istio-access-logs.md
- Add UI instructions for the Istio Access Logs tutorial
[#582](https://github.com/kyma-project/istio/issues/582)
=> Add UI instructions to the Istio Access Logs tutorial

.github/ISSUE_TEMPLATE/istio_update.md
- Add AC to istio update issue template to verify Istio feature phases
=> Update istio update issue template

.github/dependabot.yml
- Update dependabot to release 1.5
=> Update dependabot to release 1.5

docs/user/_sidebar.md, docs/user/troubleshooting/README.md
- Add a tutorial to the sidebar
=> Add tutorial to sidebar

docs/user/_sidebar.md
- Correct the link to the Basic Diagnostics guide in the sidebar
=> Correct a link in the sidebar

.github/workflows/pull-gitleaks.yaml, .gitleaks.toml
/kind chore
/area ci
Add gitleaks to repo
=> chore: add gitleaks to repo

.github/workflows/main-integration.yaml, .github/workflows/pull-integration-gardener.yaml, .github/workflows/pull-integration.yaml, .github/workflows/pull-request.yaml
- Add ignore for dot files to prevent running tests when no manager image is build
=> Ignore dot files workflows that run tests 

scripts/publish_assets.sh
- Set correct manager image in istio-manager.yml release artifact
=> Fix manager release artifact

scripts/publish_assets.sh
(cherry picked from commit 4e6a912a0a52b70381eeb4b55926d16920dd2556)
- Cherry-pick https://github.com/kyma-project/istio/pull/747
=> Fix manager release artifact on main

docs/contributor/adr/0000-istio-operator-design.md, docs/contributor/adr/0002-istio-cr-status-improvements.md
=> Fix links in the adr folder

.github/workflows/create-release.yaml
add experimental tagging in Create lightweight tag step
=> workflows: add experimental tagging

docs/user/operation-guides/02-30-enable-istio-access-logs.md
- Update Kyma dashboard instructions
=> Update Kyma dashboard instructions

.github/workflows/create-release.yaml
- workflows: add experimental tagging (#766)
=> workflows: add experimental tagging (#766)

config/manager/manager.yaml
- Set up priority class for Istio manager
=> Set up priority class for istio manager

internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
- Switch to the default cni pair pods configuration to repair the pods
https://istio.io/latest/docs/setup/additional-setup/cni/#race-condition--mitigation
=> Switch to the default cni pair pods configuration to repair the pods

docs/contributor/01-00-installation.md, tests/ui/scripts/k3d-local-dev.sh
- Deprecate kyma provision k3d command
- https://github.com/kyma-project/kyma/issues/18652
=> Deprecate kyma provision k3d command

docs/user/troubleshooting/03-70-reconciliation-fails-on-istio-install.md
- Add troubleshooting guide on how to fix issue with failing install phase due to modified Istio resource template with additional container in the pods
=> Istio troubleshooting guide on install fail due to mod resource

config/ui-extensions/kustomization.yaml, config/ui-extensions/requestauthentications/dataSources, config/ui-extensions/requestauthentications/details, config/ui-extensions/requestauthentications/form, config/ui-extensions/requestauthentications/general, config/ui-extensions/requestauthentications/kustomization.yaml, config/ui-extensions/requestauthentications/translations, docs/release-notes/1.7.0.md, tests/ui/cypress.config.ts, tests/ui/fixtures/pod-httpbin-sleep.yaml, tests/ui/support/input.ts, tests/ui/support/k8sclient/commands.ts, tests/ui/support/k8sclient/index.ts, tests/ui/support/k8sclient/pod.ts, tests/ui/support/navigation.ts, tests/ui/support/resource/commands.ts, tests/ui/support/resource/index.ts, tests/ui/support/resource/requestAuthentication.ts, tests/ui/support/resource/serviceEntry.ts, tests/ui/support/resource/sidecar.ts, tests/ui/tests/requestAuthentications.spec.ts
- Add UI for Request Authentication.
- Add retries for UI tests to handle flaky tests.
- https://github.com/kyma-project/istio/issues/581
=> Add Request Authentication UI

docs/user/troubleshooting/03-70-cannot-connect-to-hana-db.md
- Create a troubleshooting guide for issues with connection to Hana DB
=> Hana DB connectivity troubleshooting guide

config/ui-extensions/istios/general
- Unify Istio CR's description and the link to the Istio documentation to be consistent with all CR descriptions in Kyma dashboard
[Unify CRs' descriptions in Busola #18321](https://github.com/kyma-project/kyma/issues/18321)
=> Unify CRs description in Kyma dashboard

docs/user/00-10-overview-istio-controller.md
- Add information about upgrades and downgrades
=> Add info about upgrades and dowongrades

.github/workflows/main-integration.yaml, .github/workflows/performance-test.yaml, .github/workflows/pull-integration-gardener.yaml, hack/ci/provision-gardener.sh, hack/ci/shoot_aws.yaml, hack/ci/shoot_gcp.yaml
- Deprecate `kyma provision gardener`
- https://github.com/kyma-project/kyma/issues/18674
=> Deprecate kyma provision gardener

hack/ci/shoot_aws.yaml, hack/ci/shoot_gcp.yaml
- Use the default Gardener network addresses
=> Use the default Gardener network addresses

.github/workflows/main-integration.yaml, .github/workflows/performance-test.yaml, .github/workflows/pull-integration-gardener.yaml, tests/integration/scripts/gardener-kubeconfig.sh
- Gardener live kubenconfig
- Update project name
=> Run tests on Gardener live

config/ui-extensions/telemetries/general, docs/release-notes/1.6.3.md, main.go, tests/ui/support/navigation.ts, tests/ui/tests/virtualServices.spec.ts
=> Fix Busola UI

tests/ui/tests/virtualServices.spec.ts
- Skip VirtualService UI test after changes in Busola to unblock PRs
=> Skip VirtualService tests

.github/workflows/rollout-module.yaml
=> Fix typo in rollout module

README.md, api/v1alpha2/compatibility_mode.go, docs/user/00-10-overview-istio-controller.md, docs/user/04-00-istio-custom-resource.md, docs/user/README.md
- Remove ENABLE_EXTERNAL_NAME_ALIAS from the compatibility mode envs
- Move docs
=> Remove one of the compatibility envs and move docs

README.md, docs/user/README.md
=> Fix readme formatting

.github/ISSUE_TEMPLATE/istio_update.md, .github/dependabot.yml
- Exclude k8s.io dependencies from Dependabot bumps
=> Exclude k8s.io dependencies from Dependabot bumps

docs/user/troubleshooting/03-70-reconciliation-fails-on-istio-install.md
=> Use title case

docs/contributor/draft/rate-limiting-poc/04-global-rate-limiting-memcached.md, docs/contributor/draft/rate-limiting-poc/05-global-rate-limiting-valkey.md, docs/contributor/draft/rate-limiting-poc/06-sum-up-rate-limiting.md, docs/contributor/draft/rate-limiting-poc/perf_tests/global/memcached-gateway/summary-no-sidecar.html, docs/contributor/draft/rate-limiting-poc/perf_tests/global/memcached-gateway/summary-sidecar.html, docs/contributor/draft/rate-limiting-poc/perf_tests/global/memcached-sidecar/summary-no-sidecar.html, docs/contributor/draft/rate-limiting-poc/perf_tests/global/memcached-sidecar/summary-sidecar.html, tests/performance/load-testing/templates/rate-limit-memcached.yaml, tests/performance/load-testing/values.yaml
- Add Memcached rate limiting
See #826
=> Add envoy Memcached rate limiting

.github/workflows/rollout-module.yaml
- Fix experimental rollout of Istio module
=> Fix experimental rollout

.github/dependabot.yml
- Update Dependabot config to latest release branch
=> Update release branch in Dependabot config

.github/workflows/rollout-module.yaml
- Change the Pull Request label to a selection
=> Change the Pull Request label to a selection in the module rollout workflow

.github/pull-request-template.md
- Add Pre-Merge Checklist to the PR template
=> Add Pre-Merge Checklist to the PR template

tests/performance/Readme.md
Quick readme for future performance tests scenarios.
=> Add information about Istio Ingressgateway scaling

.github/actions/build-manager-image/action.yaml, .github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test/action.yaml, .github/actions/load-manager-image/action.yaml, .github/actions/upgrade-integration-test/action.yaml, .github/workflows/pull-integration-gardener.yaml, .github/workflows/pull-integration.yaml, .github/workflows/pull-request.yaml, .github/workflows/ui-tests.yaml, tests/ui/scripts/k3d-ci-kyma-dashboard-integration.sh
=> Image build

Makefile
- Fix timeout that happened on a [recent job run](https://github.com/kyma-project/istio/actions/runs/9772303038/job/26976513951)
=> Increase main testsuite timeout to avoid failing job

.github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test/action.yaml, .github/actions/upgrade-integration-test/action.yaml, .github/workflows/pull-request.yaml
- Only import image to k3d when we run it on pull_request, since we are using the remotely build image by prow on main.
=> Ignore k3d import for main build

.github/workflows/pull-request.yaml
- Update name of check-build-image job in the pull-request workflow to remove "wait"
=> Rename check-build-image job in PR workflow

.github/workflows/ui-tests-periodic.yaml
/kind bug
/area ci
* fixes bug where $IMG had incorrect registry prefix
* adds docker pull command to ensure that image is in local docker context before importing
=> bug: fix incorrect prefix for image

hack/ci/gardener-perf-test.sh, tests/performance/Makefile, tests/performance/istio-max-replicas.yaml, tests/performance/load-testing/templates/httpbin.yaml
- Fix issues in performance test
=> Adapt performance test

docs/user/operation-guides/02-30-enable-istio-access-logs.md
The istio telemetry API is stable and released, so it is time to update the documentation accordingly
- Update of any usage of telemetry API to v1 stable version
=> Use stable version for istio telemetry API in docs

.github/workflows/pull-integration-gardener.yaml
- Use ref from PR for building image in Gardener integration test PR workflow
=> Use correct commit for PR image build

docs/user/tutorials/01-00-x-forwarded-for-header.md, docs/user/tutorials/01-10-external-authorization-provider.md, hack/managed-kyma-migration/readme.md
=> Change enable and disable to add and delete in the istio repo

.github/workflows/update-sec-scanner.yaml
=> Fix schedule configuration for update sec-scanners-config.yaml

docs/user/_sidebar.md, docs/user/tutorials/01-20-expose-httbin-gateway-api.md, docs/user/tutorials/01-30-expose-tcp-gateway-api.md
- tutorial for exposing httpbin with gateway API
- tutorial for exposing TCP workload
https://github.com/kyma-project/istio/issues/895
=> tutorials for exposing workloads with gateway API

docs/contributor/adr/0008-rate-limit.md
- Remove `context` field from RateLimit CR
- Make `workloadSelector` mandatory and  remove support for scoping of RateLimit CR across namespaces
- `enforce` should be optional with `true` as default
- Add support for rate limiting by path and header value
- Restrict RateLimit CR usage to one per workload
- Remove metrics from the scope of the ADR
=> Rate limit ADR update

hack/ci/provision-gardener.sh
/kind feature
/area ci
Add retry logic in creating and waiting for gardener cluster, just as in api-gateway repo.
https://github.com/kyma-project/api-gateway/blob/main/tests/integration/scripts/provision-gardener-gh.sh
=> feat: update provision-gardener.sh with retry logic

docs/user/tutorials/01-20-expose-httbin-gateway-api.md, docs/user/tutorials/01-30-expose-tcp-gateway-api.md
- Fix the rendering of code blocks
=> Fix the rendering of code blocks

api/v1alpha1/istio_types.go, config/crd/bases/operator.kyma-project.io_istios.yaml
- As a follow-up on the migration procedure for Istios CRD, we unserve v1alpha1 in CRD
https://github.com/kyma-project/istio/issues/642
=> Unserve v1alpha1 in CRD

docs/user/migration/external-name-alias.md
- Migration guide for Service ExternalName Istio changed behavior
=> Migration guide for Service ExternalName Istio changed behavior

.github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test/action.yaml, .github/actions/provision-k3d-cluster/action.yaml, .github/actions/upgrade-integration-test/action.yaml, .github/workflows/main-integration.yaml, .github/workflows/pull-integration-gardener.yaml, .github/workflows/pull-integration.yaml, .github/workflows/pull-request.yaml, pkg/lib/sidecars/test/restart_test.go
- bump k8s version in the int tests
- introduce custom k3d provisioning action
=> cicd: bump k8s version in the int tests

hack/ci/provision-gardener.sh
- Fix gardener provision bash scripts
=> Fix gardener provision bash scripts

docs/release-notes/1.8.3.md, docs/user/00-40-overview-istio-setup.md, internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml, internal/istiooperator/istiooperator.go
* Change certificate key size to 4096 bits
* Add docs
* Add RN
* Update docs/release-notes/1.8.3.md
https://github.com/kyma-project/istio/issues/969
=> Change certificate key size to 4096 bits (#984)

.github/workflows/main-integration.yaml, .github/workflows/verify-commit-pins.yaml
- build manager images using image-builder on main branch
=> cicd: build manager with image builder on main

Dockerfile
- Kaniko uses /workspace as a reserved directory. Therefore PR provides Dockerfile adjustment
=> cicd: Dockerfile adjustment

docs/user/operation-guides/02-30-enable-istio-access-logs.md
- Last refactoring spoiled the example config for enabling access logs for the whole mesh, fixed it
=> docs: Fix access logs for entire mesh instructions

docs/user/_sidebar.md, docs/user/migration/external-name-alias.md
- The **disable-external-name-alias** annotation becomes deprecated -> this PR adjusts the migration guide accordingly
- Add the migration guide to the sidebar
=> Add ExternalName migration blog post to the sidebar

.github/workflows/create-release.yaml
- Move image build from steps to jobs
=> bug: move image build from steps to jobs

.github/workflows/pull-integration-gardener-release.yaml
- separate int gardener tests between regular and release PRs
=> cicd: separate int gardener tests between regular and release PRs

.github/workflows/create-release.yaml, .github/workflows/pull-integration-gardener-release.yaml, .github/workflows/pull-integration-release.yaml, .github/workflows/pull-request-release.yaml
- Add pipeline workflow for the release branch
=> Add pipeline workflow for the release branch

.github/workflows/pull-request-release.yaml
- change job for environment key in workflow
=> change job for environment key in workflow

.github/workflows/pull-integration-gardener-release.yaml, .github/workflows/pull-request-release.yaml
- Remove redundant job and fix typo
=> Remove redundant job and fix typo

.github/workflows/pull-request-release.yaml
=> Workflow improvements

.github/workflows/create-release.yaml, .github/workflows/main-integration.yaml, .github/workflows/pull-integration-gardener-release.yaml, .github/workflows/pull-integration-release.yaml, .github/workflows/pull-request-release.yaml
- cherry pick #1010 #1024 #1027 #1029 #1031 #1035
=> Cherry pick workflows

.github/workflows/pull-integration-release.yaml
=> Fix parameter passed to action by release int workflow

.github/workflows/pull-integration-release.yaml
=> Fix ref in workflow

.github/workflows/pull-integration-release.yaml
=> Fix ref in workflow (#1038)

api/v1alpha1/istio_types.go, api/v1alpha2/istio_types.go, config/crd/bases/operator.kyma-project.io_istios.yaml
- Add proper categories for telemetry CRDs according to linked ADR
- https://github.com/kyma-project/community/issues/912
=> feat: Add proper categories for CRDs

.github/ISSUE_TEMPLATE/istio_update.md
=> Update Istio bump template

.github/workflows/pull-request-release.yaml
- Remove security scanner config from ignored files on the release pull request pipeline
=> Remove sec scanner config from ignored files on rel pr pipeline

.github/workflows/create-release.yaml
- Fix permissions for create release workflow
=> Fix permissions for create release workflow

.github/workflows/create-release.yaml
=> Cherry pick fix of create rel workflow permissions

internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
- Increase certificate key size for mesh-to-mesh communication
https://github.com/kyma-project/istio/issues/969
https://github.com/istio/istio/issues/53326
=> Increase certificate key size for mesh-to-mesh communication

.github/workflows/main-integration.yaml, .github/workflows/pull-integration-gardener.yaml, .github/workflows/pull-request-release.yaml, .github/workflows/pull-request.yaml, .github/workflows/sync-external-images.yaml, docs/contributor/04-30-ci-cd.md, external-images.yaml
- Add workflow for image syncer
- Ignore new file with images to sync in existing workflows
=> Add new workflow for image syncer

docs/contributor/04-30-ci-cd.md
=> Add link for sync-external-images to CI/CD docs

.github/ISSUE_TEMPLATE/istio_update.md
- Add information about syncing external Istio images to the Kyma registry and remove AC about zero downtime test as it's now part of automated testing.
=> Update Istio upgrade issue template

docs/contributor/adr/0009-egress-gateway.md
- Create ADR for Istio egress-gateway component
- https://github.com/kyma-project/istio/issues/1070
=> Create ADR for Istio `egressGateway` component

.github/ISSUE_TEMPLATE/issue.md
- Missing gh required issue template metadata
=> Fix broken issue template

sec-scanners-config.yaml
- Bump istio-manager main image for sec-scanners-config.yaml
=> Bump istio-manager main image for sec-scanners-config.yaml

internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
- In order to simplify Dynatrace integration with Kyma Telemetry module, we need to enable the [PrometheusMerge](https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging) feature. Check [here](https://github.com/kyma-project/telemetry-manager/issues/1468) for more details.
=> feat: Enable prometheusMerge feature

sec-scanners-config.yaml
=> chore: update sec-scanners-config.yaml

.github/workflows/create-release.yaml, .github/workflows/performance-test.yaml, .github/workflows/ui-tests-periodic.yaml
- Build correct images for performance tests, UI tests and releases
=> Update repository path of images to match new format

sec-scanners-config.yaml
- Bump istio main image for sec-scanners-config.yaml
=> Bump istio main image for sec-scanners-config.yaml

tests/integration/scripts/test-zero-downtime-upgrade.sh
- Reduce flakiness of zero downtime verification when running upgrade integration test
=> Reduce upgrade test flakiness

hack/ci/provision-gardener.sh
- Increase timeout to 25m to avoid flakiness due to cluster creation timeouts
=> Increase timeout for provisioning Gardener cluster

docs/release-notes/1.11.0.md, docs/user/tutorials/01-00-x-forwarded-for-header.md
- Update docs and add release notes
#937
=> Add docs about zone based podAntiAffinity rules

.github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test/action.yaml
- Add manager and istio logs when integration test fail
=> Add manager and istio logs in tests

external-images.yaml
=> Add Istio 1.24.1 to images

.github/workflows/pr-add-dependabot-to-project.yaml
/kind feature
/area ci
Run workflow on pull request to automate adding dependabot PRs to board.
=> feat: workflow to add dependabot PRs to project

.github/workflows/update-sec-scanner.yaml
/kind bug
/area ci
Change schedule to every friday at 15:21 UTC.
#925
=> bug: change schedule of update-sec-scanner.yaml

.github/workflows/pull-add-bot-prs-to-project.yaml
/kind feature
/area ci
Extend pull-add-bot-prs-to-project.yaml to add PRs from kyma-goat-bot user.
=> feat: add kyma-goat-bot user to autoadd PRs to board

.github/workflows/pull-request-release.yaml
/kind bug
/area ci
Fix UI tests by uploading an image built by image builder into the local Docker context
=> bug: upload image from image-builder

.github/workflows/pull-request-release.yaml
/kind bug
/area ci
Fix UI tests by uploading an image built by image builder into the local Docker context
=> bug: upload image from image-builder (#1166)

.github/dependabot.yml
- Update Dependabot release branch to release-1.11
=> Update release branch in Dependabot

docs/contributor/02-10-testing-strategy.md, docs/contributor/adr/0010-testing-strategy.md
- Testing strategy for Istio module
=> Testing strategy for Istio module

internal/istiooperator/istio-operator.yaml
- Run egress deployments on different nodes and zones if possible
#1159
=> Add egress-gateway affinity

.github/actions/slack-notification-failed-workflow/action.yaml
- Add owner to the slack failed tests notification
=> Add owner to the slack failed tests notification

.github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test/action.yaml, .github/workflows/call-integration-tests.yaml, .github/workflows/call-release-pr-integration-gardener.yaml, .github/workflows/main-integration.yaml, .github/workflows/pull-integration-gardener.yaml
=> Bump k8s int tests

docs/user/00-15-overview-istio-setup.md, internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
- Add necessary fields to egress-gateway
=> Adapt HPA and resources of egress gateway

tests/testcontext/config.go
- Increase default test timeout
=> Increase default test timeout

.github/workflows/call-ui-tests.yaml
- UI tests workflow fix for checkout without fetch-depth
=> UI tests workflow fix for checkout without fetch-depth

docs/release-notes/1.13.0.md
- Create 1.13.0 release notes
- Add switch to IOP
=> Create 1.13.0 release notes

.github/dependabot.yml
- Bump dependabot for Release 1.13
=> Bump dependabot for Release 1.13

tests/integration/hooks.go, tests/integration/scenario.go
- Show Istio CR status when integration tests are failing
=> Print Istio CR in failed tests

.github/workflows/call-unit-lint-head-ref.yaml, .github/workflows/release-pr.yaml
- Use head ref for release PR as base
=> Use head ref for release PR as base

.github/actions/slack-notification-failed-workflow/action.yaml
- Add additional info to the failed run slack notification
=> Add additional info to the failed run slack notification

README.md, docs/assets/istio-whitelogo-bluebackground-framed.svg, docs/user/00-10-compatibility-mode.md, docs/user/README.md
- Update information on Istio version
=> Update information on Istio version

docs/user/troubleshooting/03-40-incompatible-istio-sidecar-version.md, internal/restarter/sidecars.go
- Update the Incompatible Istio Sidecars troubleshooting guide
=> Update the Incompatible Istio Sidecars troubleshooting guide

.github/workflows/release-create-release.yaml
* Fix yq in the create release workflow
* Add nice log
- Fix release workflow yq (#1274)
=> Fix release workflow yq (#1274)

.github/dependabot.yml
- Update dependabot to release-1.14 branch
=> Update dependabot to release-1.14 branch

docs/release-notes/1.13.2.md, internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
- Set new metric interval
#1265
=> Set global metrics rotation interval to 6h

.github/workflows/release-create-release.yaml, Makefile
Remove yq usage from release-create-release.yaml workflow
Remove yq from Makefile
=> chore: remove yq from release-create-release.yaml

.github/actions/k8s-compatibility-test/action.yaml, tests/integration/main_test.go
- Bump k8s version in compatibility test
=> Bump k8s version in compatibility test

docs/user/_sidebar.md
- add egress tutorials to the sidebar
=> add tutorials to sidebar

docs/contributor/adr/0010-module-status.md
- ADR for Processing status handling of Istio module
=> ADR for Processing status handling of Istio module

docs/user/tutorials/01-45-enable-istio-access-logs.md
- extended the access logs guide to explain filtering
=> docs: Explain access logs filtering

docs/release-notes/1.11.0.md
- Fix a link to Istio 1.24.1 release
=> Fix link to Istio 1.24.1 release

.github/workflows/release-create-release.yaml, .github/workflows/release-pr.yaml, .github/workflows/schedule-performance-test.yaml, .github/workflows/schedule-ui-tests-periodic.yaml
- Fix missing permissions for image-builder
=> Fix missing permissions for image-builder

.github/workflows/release-create-release.yaml, .github/workflows/release-pr.yaml, .github/workflows/schedule-performance-test.yaml, .github/workflows/schedule-ui-tests-periodic.yaml
=> Fix missing permissions for image-builder (#1326)

.github/workflows/post-main-workflow.yaml, .github/workflows/release-create-release.yaml, .github/workflows/release-pr.yaml, .github/workflows/schedule-performance-test.yaml, .github/workflows/schedule-ui-tests-periodic.yaml
- Add missing permission for image-builder
=> Add missing permission for image-builder

.github/workflows/post-main-workflow.yaml, .github/workflows/release-create-release.yaml, .github/workflows/release-pr.yaml, .github/workflows/schedule-performance-test.yaml, .github/workflows/schedule-ui-tests-periodic.yaml
=> Cherry pick - add missing permission for release

.github/workflows/call-unit-lint.yaml
- Ensure linter version to mitigate breaking changes on rel branch
=> Ensure linter version to mitigate breaking changes on rel branch

.github/workflows/call-unit-lint-head-ref.yaml
- Ensure lint version to avoid breaking changes
=> Ensure lint version to avoid breaking changes

sec-scanners-config.yaml
- Updated security config for 1.15
=> Istio release 1.15 security config

.github/workflows/call-integration-tests.yaml
- Fix e2e gardener AWS tests in the release workflow, to make it able to run `e2e-test` make target (egress connectivity tests)
=> Fix e2e test in the rel workflow

.github/workflows/call-integration-tests.yaml
- Partial adjustment of the rel pipeline
=> Partial adjustment of the rel pipeline

.github/actions/get-latest-sha/action.yaml, .github/workflows/schedule-main-integration.yaml, tests/performance/Makefile
- adjusted if in performance tests.
=> Changed if for perf tests.

docs/user/tutorials/01-10-external-authorization-provider.md, docs/user/tutorials/01-20-expose-httbin-gateway-api.md, docs/user/tutorials/01-50-send-requests-using-egress.md, docs/user/tutorials/01-55-send-requests-using-egress-and-mtls.md
- Prepare Istio tutorials for moving to Tutorial Navigator
=> Prepare Istio tutorials for moving to Tutorial Navigator

docs/user/tutorials/01-20-expose-httbin-gateway-api.md
- fixing mistakes made with https://github.com/kyma-project/istio/pull/1349
=> Fix code snippets in Gateway API tutorial

controllers/elb_config_map_predicate.go, controllers/istio_controller.go, docs/user/tutorials/01-60-enable-nlb-load-balancer.md, internal/clusterconfig/clusterconfig.go, internal/clusterconfig/clusterconfig_test.go, internal/reconciliations/istio_resources/proxy_protocol_envoy_filter.go, internal/reconciliations/istio_resources/proxy_protocol_envoy_filter_test.go, internal/reconciliations/istio_resources/reconciliation.go, internal/reconciliations/istio_resources/reconciliation_test.go, internal/resources/resources.go
- Add `elb-deprecated` CM based switch to allow migration from ELB on AWS
- Switch to NLB on deletion of CM
=> feat: Conditional switch to NLB load balancer

docs/release-notes/1.16.0.md
=> NLB release notes

.github/workflows/call-pull-e2e.yaml, .github/workflows/call-release-pr-integration-gardener.yaml, .github/workflows/call-release-pr-integration.yaml, .github/workflows/call-ui-tests.yaml, .github/workflows/call-unit-lint-head-ref.yaml, .github/workflows/call-unit-lint.yaml, .github/workflows/call-verify-commit-pins.yaml
- Remove tj-changed action from workflows
=> Remove tj-changed action from workflows

tests/integration/features/aws-suite/xff_header.feature
- Remove obsolete tests after changing load balancer default type on AWS
=> Remove obsolete tests after changing load balancer default type on AWS

go.mod
- Synchronized go version with Dockerfile, removed obsolete toolchain declaration
=> Sync go version with Dockerfile, removed obsolete toolchain declaration

.github/actions/e2e-test-gardener/action.yaml, .github/actions/k8s-compatibility-test-aws/action.yaml, .github/actions/perf-test-gardener/action.yaml, .github/workflows/schedule-cleanup-garden.yaml, hack/ci/scripts-v2/cleanup-garden.sh, hack/ci/scripts-v2/shoot_aws.yaml, hack/ci/scripts-v2/shoot_gcp.yaml
- Skip cluster deletion in case of test failure
- Added independent Gardener cleanup job
=> Skip cluster deletion after test failure, added Gardener cleanup job

tests/integration/hooks.go, tests/integration/main_test.go
- Skip scenario hooks that clean up resources if test failed to allow debugging
=> Skip cleanup in case of test failure (similarly to API Gateway)

docs/release-notes/1.16.1.md, internal/clusterconfig/clusterconfig.go, internal/clusterconfig/clusterconfig_test.go, internal/reconciliations/istio/install.go, internal/reconciliations/istio_resources/reconciliation.go, internal/reconciliations/istio_resources/reconciliation_test.go
=> Fix XFF CCEE bug cherrypick

internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml, internal/reconciliations/istio/install.go, internal/reconciliations/istio/metadata.go, internal/reconciliations/istio/reconciliation_test.go, internal/restarter/sidecars_test.go, pkg/lib/gatherer/gatherer.go, pkg/lib/gatherer/gatherer_test.go
- Check only for version of Control Plane pods belonging to Istio
- https://github.com/kyma-project/istio/issues/1280
=> fix: Check only for version of Control Plane pods belonging to Istio

docs/user/00-00-istio-sidecar-proxies.md
=> Add policy restart docs

api/v1alpha2/conditions.go, api/v1alpha2/istio_types.go, controllers/istio_controller.go
- Check if oldest CR is found.
=> Check if oldest CR is found

.github/actions/e2e-test-k3d/action.yaml
- Update k3s version to 1.31.8
=> Update k3s version to 1.31.7

docs/user/00-00-istio-sidecar-proxies.md
=> Fix formatting of a note

.github/actions/e2e-test-k3d/action.yaml, .github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test/action.yaml, .github/actions/upgrade-integration-test/action.yaml, internal/clusterconfig/clusterconfig.go, internal/clusterconfig/clusterconfig_test.go, sec-scanners-config.yaml
* Update k3s version to 1.31.7
* Update compatibility check to 1.32
* Update CNI bin path to the new one /var/lib/rancher/k3s/data/cni
- Cherry pick https://github.com/kyma-project/istio/pull/1407
- Update security scanner
=> Update k3s version to 1.31.7 (#1407)

config/ui-extensions/istios/details
- Move the status from metadata to status
- https://github.com/kyma-project/istio/issues/1096
=> Move the status from metadata to status

config/ui-extensions/authorizationpolicies/dataSources, config/ui-extensions/authorizationpolicies/details, config/ui-extensions/requestauthentications/dataSources, config/ui-extensions/requestauthentications/details, config/ui-extensions/virtualservices/dataSources, config/ui-extensions/virtualservices/details
- adjust resource graphs for more specific information per resource
=> Adjust resource graphs.

.github/workflows/call-integration-tests.yaml, .github/workflows/call-release-pr-integration-gardener.yaml
- Adjusted scaler_min parameter for AWS to ensure that every availability zone has at least one machine (otherwise NLB Load Balancer redirects the traffic to zone without any machine and requests fail)
=> Adjusted scaler_min parameter for AWS to ensure that every availability zone has at least one machine

.github/workflows/call-integration-tests.yaml, .github/workflows/call-release-pr-integration-gardener.yaml
- Adjusted scaler_min parameter for AWS to ensure that every availability zone has at least one machine (otherwise NLB Load Balancer redirects the traffic to zone without any machine and requests fail)
=> Adjusted scaler_min parameter for AWS to ensure that every availability zone has at least one machine (#1440)

docs/user/tutorials/01-50-send-requests-using-egress.md, docs/user/tutorials/01-55-send-requests-using-egress-and-mtls.md
it was somehow lost during review
=> docs: add misssing networkpolicy docs

controllers/istio_controller.go, controllers/istio_controller_test.go, docs/release-notes/1.17.3.md, internal/status/status.go, internal/status/status_test.go, pkg/lib/sidecars/restart/replica_set_action.go, pkg/lib/sidecars/restart/restart.go, pkg/lib/sidecars/restart/restart_factory.go, pkg/lib/sidecars/restart/restart_test.go, sec-scanners-config.yaml, tests/integration/features/installation-suite/install.feature, tests/integration/features/installation-suite/uninstall.feature, tests/integration/scenario.go, tests/integration/steps/istio_cr.go
- Cherrypick of https://github.com/kyma-project/istio/pull/1437
=> fix: Sidecar restart spawning ReplicaSet every time when ReplicaSet did not finish progressing

.github/actions/slack-notification-failed-workflow/action.yaml
- Fix attempt param in the slack notification
=> Fix attempt param in the slack notification

docs/release-notes/1.18.0.md
- add release notes to Istio 1.18.0
=> Add RN 1.18.0.

docs/user/tutorials/01-50-send-requests-using-egress.md, docs/user/tutorials/01-55-send-requests-using-egress-and-mtls.md
- Fix NetworkPolicy code and note
- Fix merge conflicts caused by https://github.com/kyma-project/istio/pull/1434
=> Update egress tutorials

.github/dependabot.yml
- Dependabot configuration adjustment.
=> Dependabot adjustments

external-images.yaml
=> chore: add new istio images to external-images.yaml

tests/integration/features/aws-suite/xff_header.feature, tests/integration/features/gcp-suite/xff_header.feature, tests/integration/scenario.go, tests/integration/steps/x_forwarded_for_validation.go
- xff e2e tests now set proper Host header after previous e2e tests adjustments
=> Fix xff tests

docs/release-notes/1.20.0.md
=> Add 1.20 release notes

internal/resources/user_resources_finder.go, internal/resources/user_resources_finder_test.go
=> bug: fix Warning status caused by module's proxy-protocol EF

.github/workflows/post-main-workflow.yaml, .github/workflows/release-create-release.yaml, .github/workflows/release-istio-2.yaml, Dockerfile, Makefile
- adapt Dockerfile
- adapt workflow of image builder
- adapt make target
=> Setup for support of arm64 image building

docs/release-notes/1.20.1.md, internal/resources/user_resources_finder.go, internal/resources/user_resources_finder_test.go
=> cherry-pick #1495

external-images.yaml
- Sync istio 1.26.2 with internal registry
=> Sync istio 1.26.2 with internal registry

tests/performance/hack/puppeteer/export.js
- Move the auth basic creds to an env
=> sec: Move the auth basic creds to an env

.github/workflows/post-main-workflow.yaml, .github/workflows/release-create-release.yaml, .github/workflows/release-istio-2.yaml, Dockerfile, Makefile
- Setup for support of arm64 image building (#1497)
=> Setup for support of arm64 image building (#1497)

docs/release-notes/1.11.0.md
- Fixed a broken link to the Istio release page
=> docs: Fix broken link to the Istio release page

.github/workflows/schedule-main-integration.yaml
- Fix missing env in the schedule workflow required after recent changes in #1527
=> Fix schedule workflow missing env

.github/actions/build-manager-image/action.yaml, .github/actions/e2e-test-gardener/action.yaml, .github/actions/e2e-test-k3d/action.yaml, .github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test-aws/action.yaml, .github/actions/k8s-compatibility-test/action.yaml, .github/actions/upgrade-integration-test/action.yaml, .github/workflows/call-integration-tests.yaml, .github/workflows/call-pull-e2e.yaml, .github/workflows/post-main-workflow.yaml, .github/workflows/pull-build-push.yaml, .github/workflows/pull-request.yaml, .github/workflows/release-istio-2.yaml, Dockerfile, docs/release-notes/1.19.3.md, internal/reconciliations/istioresources/peer_authentication_mtls_test.go, internal/reconciliations/istioresources/proxy_protocol_envoy_filter_test.go, internal/resources/disclaimer_annotation_test.go, internal/resources/resources.go, internal/resources/resources_test.go, internal/resources/test_files/resource_after_labels.yaml, internal/resources/test_files/resource_before_labels.yaml, tests/integration/features/installation-suite/install.feature, tests/integration/scenario.go, tests/integration/steps/resource.go, tests/integration/testsupport/environments.go
=> backport: bug: Fix labels reconciliation in resource manager (#1527)

.github/pull-request-template.md
=> Improve pre-merge checklist

.github/actions/k8s-compatibility-test-aws/action.yaml, .github/actions/k8s-compatibility-test/action.yaml
- Make deprecation report to be uploaded on failure
=> Make deprecation report to be uploaded on failure

.github/actions/k8s-compatibility-test-aws/action.yaml, .github/actions/k8s-compatibility-test/action.yaml
- Fix syntax issue in the compatibility tests action
=> Fix compatibility actions

.github/actions/k8s-compatibility-test/action.yaml
- Ignore endpoints in k3d compatibility test
=> Ignore endpoints in k3d compatibility test

external-images.yaml
- Sync Istio 1.27.0 with registry
=> Sync Istio 1.27.0 with registry

external-images.yaml
- Add 1.27.1 images to image syncer
Consider all the following items. If your contribution violates any of them, or you are not sure about it, add a comment to the PR.
=> Add 1.27.1 images to image syncer

docs/user/tutorials/01-10-external-authorization-provider.md
- fixed bad formatted md not valid in Vitepress (markdown-it)
Consider all the following items. If your contribution violates any of them, or you are not sure about it, add a comment to the PR.
https://github.com/kyma-project/kyma/pull/18817
=> fixed bad formatted md not valid in Vitepress (markdown-it)

docs/user/troubleshooting/03-45-jobs-cant-finish.md, docs/user/troubleshooting/03-46-init-containers-cant-access-network.md
- Fix links to troubleshooting guides
Consider all the following items. If your contribution violates any of them, or you are not sure about it, add a comment to the PR.
=> Fix links to troubleshooting guides

docs/user/00-20-istio-proxy-as-native-sidecar.md
- Update Regular and Native Sidecar Containers after TW review
Consider all the following items. If your contribution violates any of them, or you are not sure about it, add a comment to the PR.
=> Update Regular and Native Sidecar Containers after TW review
