operator/api/v1alpha1/istio_merge.go, operator/api/v1alpha1/istio_merge_test.go
- do not throw panic when passing iop file without defaultConfig set
=> Allow merge with empty defaultConfig in istio Operator

operator/pkg/lib/sidecars/pods/get_test.go, operator/pkg/lib/sidecars/test/helpers/fake_client_indexer.go, operator/pkg/lib/sidecars/test/test_client.go
Currently some of the tests fail. We didn't have a test job configured for this repo when this was introduced, so we didn't see it.
The tests were failing since the update of sigs.k8s.io/controller-runtime from 0.13.1 to 0.14.0 (https://github.com/kyma-project/istio/pull/46).
The root cause why tests are failing is, that a support for indexes was introduced to the fake client (https://github.com/kubernetes-sigs/controller-runtime/pull/2025). Before the field selectors were just ignored. After adding the change in the fake client field selectors unknown to the fake client will cause an error.
- Add the status.phase field selector fake to the fake client
=> Add support for pod status.phase field selector in fake client

Makefile, hack/ci/gardener-integration.sh, hack/ci/jobguard.sh
- Prepare make command and shell script for provisioning Gardener cluster and running Istio tests
- Script is ready for running on different cluster providers so it can be reused for autoscaler compliancy check later
- https://github.com/kyma-project/test-infra/issues/7564
=> Add script for running istio integration tests on gardener

Makefile, config/manager/manager.yaml, tests/integration/features/istio/configuration.feature
- Increase limits for memory and CPU usage by Istio manager
- Increase test timeout
- Make proxy test more resilient by making sure deployment is ready before running restart
**Metrics**
- Based on Prometheus metrics:
- https://github.com/kyma-project/istio/issues/157
=> Increase memory and CPU limits for manager

.github/workflows/main-cache.yaml, .github/workflows/main.yaml, .github/workflows/pull-request.yaml, .github/workflows/verify-commit-pins.yaml
With our current config we create a cache with go dependencies for every PR. This caches can only be re-used in the same PR. That means the first workflows in a PR always have to download the dependencies, even when there are not changes to the dependencies.
To avoid that we can leverage the built-in usage of caches from the main branch. 
> Access restrictions provide cache isolation and security by creating a logical boundary between different branches or tags. Workflow runs can restore caches created in either the current branch or the default branch (usually main).  
[GitHub cache docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
- Add main workflow with a step to run go build and …
=> GitHub Actions cache build on main branch

go.mod, go.sum, internal/clusterconfig/clusterconfig.go
The URL of the module mergo changed (more info can be found in the [release](https://github.com/imdario/mergo/releases/tag/v0.3.16)).
We can also see issue in the [latest dependabot run](https://github.com/kyma-project/istio/network/updates/693059567) mentioning that the module path changed.
- Update mergo module path
=> Update mergo module URL to fix dependabot error

docs/user/01-10-istio-controller-parameters.md
- Change the size of headings in the `Istio Controller parameters` document so that they can be displayed on the sidebar of the kyma-docs website
=> Change the size of headings

.github/dependabot.yml
- We need to keep the ctrl runtime version in sync with the version used by the Istio lib, that's why we should ignore it in Dependabot
=> Ignore controller runtime updates in dependabot

docs/release-notes/1.1.0.md, manifests/istio-operator-template-light.yaml
- Enable hpa for light install
=> Enable HPA for light module installation

config/manager/kustomization.yaml, config/manager/manager.yaml, config/manager/metrics_service.yaml, main.go
- Adds Istio operator metrics service so we can export operator metrics with runtime-monitoring-operator
=> Add Istio operator metrics service

tests/integration/features/istio/production/upgrade-suite/istio_upgrade.feature, tests/integration/manifests/fail-operator-manifest.yaml, tests/integration/scenario.go, tests/integration/steps/operator.go
- Fix upgrade test by not merging with existing resources but apply new manifest resources
- This way we can get errors when there are some inconsistencies, problems if we apply changes that can not be applied by k8s
=> Change upgrade test to not merge manifest with old one

controllers/istio_controller.go, controllers/istio_controller_test.go, tests/integration/features/istio/production/main-suite/istio_installation.feature
- Warning status on an Istio CR when there is more than one defined
#613
=> Set state to warning when more than one Istio CR is defined

docs/user/operation-guides/02-30-enable-istio-access-logs.md
- Add a section on how to enable access logs for the whole service mesh
- Add a verification call to the examples as for retrieval of the resource the full qualified name must be used. The resource name is clashing with a resource of the telemetry module and people are confused that there is no resource available after creation.
=> docs: Enable access logs for the whole mesh and verify the telemetry resource

Makefile, docs/release-notes/1.6.2.md, docs/release-notes/1.7.0.md, go.mod, go.sum, internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml, sec-scanners-config.yaml
=> Upgrade to Istio 1.21.2

.github/ISSUE_TEMPLATE/istio_update.md, README.md, docs/release-notes/template.md, docs/user/README.md, scripts/create_draft_release.sh, scripts/get_module_envoy_version.sh, scripts/get_module_istio_version.sh
- Automation to add Istio and Envoy version for new releases
- Add Istio and Envoy version to README
- Update issue template for Istio updates to include updating the versions in the README
- https://github.com/kyma-project/istio/issues/610
=> Istio Version documentation

config/ui-extensions/telemetries/general, tests/ui/support/navigation.ts
With https://github.com/kyma-project/istio/issues/579 a new UI for istio telemetry resources was introduced. The UI is in conflict with Kyma telemetry resources as they share the same URL path.
With https://github.com/kyma-project/telemetry-manager/pull/1092 we tried to change the path for the kyma resources. The actual navigation node is fixed indeed, however, the module UI of the dashboard does ignore that setting and build up links on the plural of the CRD and is still broken.
As fixing the dashboard will take time, this PR is adjusting the path for the istio resource as they are not used in the module UI, so that the kyma resource path can be reverted back.
- change path from "telemetries" to "istiotelemetries" for telemetry UI …
=> fix: Use a custom path for telemetries UI to avoid conflicts with kyma telemetry resources

tests/integration/hooks.go, tests/integration/scenario.go
- Disable hook that verifies that the controller was not restarted in integration and upgrade tests. The hook introduces flakiness in the tests and therefore we should disable during investigation to unblock PRs.
=> Disable test controller restart verification hook

tests/integration/hooks.go, tests/integration/scenario.go
- Remove verifyIfControllerHasBeenRestarted  since it became unreliable on Gardener and made the tests flaky
=> Remove hook that verifies if controller was restarted in integration tests

tests/performance/Makefile
/kind bug
/area ci
* add timeout to kubectl wait for service ip. By default, it's 30 seconds which seems to be not enough.
=> bug: add timeout to kubectl wait for service ip

.github/workflows/performance-test.yaml
/kind bug
/area ci
* aadd scripts/get_latest_build_sha.sh use to perf test - for some commits build is not triggered and perf tests fail on ImagePullbackOff.
=> bug: add scripts/get_latest_build_sha.sh use to perf test

.github/workflows/update-sec-scanner.yaml
/kind bug
/area ci
fixing workflow error `error: pathspec 'autobump/sec-scanners-config' did not match any file(s) known to git`. git fetch origin is missing
=> bug: fix fetching origin in update-sec-scanner.yaml

.github/workflows/update-sec-scanner.yaml
/kind bug
/area ci
It's supposed to be `${{ secrets.GITHUB_TOKEN }}`...
=> bug: use proper secret in a workflow

docs/user/tutorials/01-20-expose-httbin-gateway-api.md, docs/user/tutorials/01-30-expose-tcp-gateway-api.md
- Improve the Gateway API tutorial
=> Fix formatting in the Gateway API tutorial

docs/release-notes/1.8.3.md, docs/user/00-40-overview-istio-setup.md, internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml, internal/istiooperator/istiooperator.go
- Change certificate key size
- Fix typo
#969 
**Info**
https://istio.io/latest/docs/ops/configuration/traffic-management/manage-mesh-certificates/
Can be tested with:
```
kubectl get secrets -n istio-system istio-ca-secret --template='{{ range $key, $value := .data }}{{ printf "%s: %s\n" $key ($value | base64decode) }}{{ end }}'
```
=> Change certificate key size to 4096 bits

.github/workflows/main-integration.yaml, .github/workflows/performance-test.yaml, .github/workflows/pull-integration-gardener-release.yaml, .github/workflows/pull-integration-gardener.yaml, .github/workflows/pull-integration-release.yaml, .github/workflows/pull-integration.yaml, .github/workflows/pull-request-release.yaml, .github/workflows/pull-request.yaml, .github/workflows/pull-unit-lint.yaml, .github/workflows/ui-tests.yaml, .github/workflows/verify-commit-pins.yaml
/kind chore
/area ci
Consolidate job statuses in PRs into one, as in api-gateway repo
Add GITHUB_TOKEN usage in workflows that use make
=> chore: consolidate job statuses in PRs into one

.github/workflows/pull-request-release.yaml, .github/workflows/pull-request.yaml
/kind chore
/area ci
Seems that when previous job fails, status job gets skipped, resulting in letting PR merge. Try to always run the job regardless the result of previous dependant jobs.
=> bug: always run status action

.github/workflows/create-release.yaml, .github/workflows/main-integration.yaml, .github/workflows/performance-test.yaml, .github/workflows/pull-integration-gardener-release.yaml, .github/workflows/pull-integration-release.yaml, .github/workflows/pull-request-release.yaml, .github/workflows/ui-tests-periodic.yaml, .github/workflows/update-sec-scanner.yaml, scripts/publish_assets.sh
/kind chore
/area ci
Separate images that we run on main/releases/pr in order to keep better isolation between the artifacts to allow introducing registry automations.
#925
=> chore: separate main and release images

internal/istiooperator/istio-operator.yaml
- Add podAntiAffinity rules to Istio IngressGateway
=> Add multizone podAntiAffinity for Istio ingressGateways

.github/workflows/update-sec-scanner.yaml
/kind bug
/area ci
There is a problem with properly assuming which tag should ba taken as the latest, because docker registry returns all tags for image only in alphabetical order. SHAs are not alphabetical, and sorting them is tedious task.
Because we build images and tag them with full commit SHA, instead of trying to fetch and sort all tags, grab latest HEAD of git repo and check if the tag exists on the repo. If it exists, update config. Otherwise, skip updating config update
#925
=> bug: fix fetching main image from registy

.github/workflows/update-sec-scanner.yaml
/kind bug
/area ci
add fetching origin refs, because apparently there are no commit history.
#925
=> bug: add refs fetch in update-sec-scanner.yaml

.github/dependabot.yml
/kind chore
/area ci
Let dependabot use its default labels
=> chore: remove custom labels from dependabot.yml

.github/workflows/update-sec-scanner.yaml
/kind chore
/area ci
something's wrong with workflows not running on PRs made by kyma-goat-bot. Change git user to kyma-goat-bot from GitHub Actions.
=> chore: change git user to kyma-goat-bot

.github/workflows/update-sec-scanner.yaml
/kind chore
/area ci
token value in actions/checkout action defaults to `github.token`. Even if I set GITHUB_TOKEN env, it will use default github actions account to interact with repo using git. Use custom token.
#925
=> chore: change default token in checkout action

internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
The enablement of the prometheusMerge feature was tested thoroughly with the Kyma telemetry feature and decided that on the current landscapes will not introduce a breaking change. Unfortunately, the analysis missed the fact that users can run a prometheus with a sidecar which is having a scrape loop for pod-based prometheus annotations, which scrapes istiofied workload using https, see https://github.com/kyma-project/examples/tree/main/prometheus for an example. Indeed, this scenario is a breaking change as after enabling the feature, the prometheus will call the new istio endpoint still with https, but the endpoint does not support TLS anymore.
This PR is reverting the change, and the feature will get introduced properly by having a configuration option which is disabled …
=> fix: Revert enabling prometheusMerge feature

Dockerfile
- Optimise manager building time by stripping symbols
=> Optimise manager building time by stripping symbols

config/samples/operator_v1alpha2_istio.yaml, docs/user/00-15-overview-istio-setup.md, internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
- Update docs and operator config
#1159
=> Fix egress resources

docs/user/00-15-overview-istio-setup.md, internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
- To avoid confusion use the same resources for both deployments 
#1159
=> Set the same resources for egress and ingress

.github/actions/slack-notification-failed-workflow/action.yaml, .github/workflows/main-integration.yaml
- Bump slack action in the failed workflow notification
- Fix reference to secrets instead of inputs in the slack notification action
- Drop .github from pathignore in the main push workflow
=> Bump slack action in the failed workflow notification

docs/user/tutorials/01-50-send-requests-using-egress.md
- Create a tutorial for egress
#419
=> Tutorial for Egress

.github/workflows/release-create-release.yaml
- Fix yq in the create release workflow
=> Fix release workflow yq

.github/workflows/call-integration-tests.yaml, .github/workflows/post-main-workflow.yaml, Makefile, pkg/lib/gatherer/gatherer.go, tests/e2e/README.md, tests/e2e/egress/egress_test.go, tests/integration/steps/deployment.go
* Add simple e2e test for egress TLS gateway
* Add small documentation on writing E2E tests from scratch
* Add new Makefile target to run E2E tests. It uses gotestsum to generate nice summary of the tests without additional effort from the developer.
* Add `test-e2e` to Matrixes of gardener tests on post and release workflows.
This tests implements the official Istio egress tutorial with TLS passthrough.
Note that this test will work only on a cluster that supports NetworkPolicy.
**K3s/K3d uses flannel as CNI. Flannel does not support NetworkPolicies very well!**
For local cluster only kind supports NetworkPolicies. If we don't want to spend a lot of money on gardener clusters, we should invest in using kind locally and in CI one day.
#1201
=> feat: egress e2e test

Makefile, tests/e2e/egress/egress_test.go
Gardener is flaky. Increase timeout to 10 min for all retryable logic.
Add `--rerun-fails` to rerun failed tests in case of flakiness, and to give infra time to potentially settle.
#1201
=> bug: increase backoff on e2e test

.github/workflows/call-integration-tests.yaml
Remove e2e-test execution for gardener GCP until issue with Gardener GCP networkPolicy is resolved.
=> bug: remove test-e2e from GCP integration tests

.github/workflows/post-main-workflow.yaml
Remove e2e-test execution for gardener GCP until issue with Gardener GCP networkPolicy is resolved.
=> bug: remove test-e2e from GCP integration tests 2

.github/workflows/schedule-main-integration.yaml
- Change cron expression in schedule main job to run one hour earlier than in the API Gateway repository to not utilize too much resources at the same time
=> Run schedule main job one hour before to not clash with Api Gateway

tests/performance/Makefile
- Wait for Ingress to respond after helm is chart is installed in the performance tests
- Added sleep command after workload deployment to postpone performance test execution (to ensure that workloads are 'ready', not only started)
- More reliable and simpler way of getting domain name
=> Wait for the ingress in the performance test, added sleep commands to ensure that workloads are ready

.github/actions/e2e-test-k3d/action.yaml
Reverts kyma-project/istio#1403
There is an incompatibility between the newest k3s and the Istio CNI
=> Revert "Update k3s version to 1.31.7"

tests/e2e/egress/egress_test.go
Gardener topology is a little bit different than standard Kubernetes one. DNS Service is working in host network mode. This disrupts the behaviour of NetworkPolicy.
This change requires the NetworkPolicy to contain the IP CIDR of services used for connectivity.
`100.104.0.0/13` is a default Service IP range when gardener cluster is created.
Tested against Gardeners on different providers, and locally in kind.
=> bug: add missing gardener IP ranges for services

internal/istiooperator/istio-operator-light.yaml, internal/istiooperator/istio-operator.yaml
The telemetry module is introducing support for OTLP based ingestion and export of logs, see https://github.com/kyma-project/telemetry-manager/issues/556. Hereby, logs collected via stdout will be shipped differently then before (protocol, attribute naming, anything) and users need to adopt.
Currently, Istio access logs are supported via printing JSON to stdout, using the "stdout-json" Istio extension provider. As users need to adopt when switching to OTLP, we directly like to add Istio access logs support via OTLP as well, so that users need to adopt once only.
This PR introduces a new Istio "envoyOtelAls" extension provider "kyma-logs" (analogue to "kyma-traces") which will push access logs to the upcoming telemetry log gateway.
There is no default format for defining …
=> feat: Enable Istio access logs via OTLP to Telemetry Log Gateway

pkg/lib/sidecars/restart/log_action.go, pkg/lib/sidecars/restart/replica_set_action.go, pkg/lib/sidecars/restart/restart_test.go
- Warning should not happen when ReplicaSet is not ready
=> fix: Warning should not happen when ReplicaSet is not ready

docs/user/04-00-istio-custom-resource.md
- Fix for the docs, there is a Ready state on IstioCR if there is no user created EF in the cluster
=> Fix docs: state of IstioCR for user resource detection

tests/performance/Makefile, tests/performance/load-testing/templates/httpbin.yaml
- added readinessProbe to httpbin
- fixed wait for readiness during deployment (previously `echo` was validated as positive condition and terminate `until`)
- fixed curl to call actual deployment not istio gateway  itself 
=> tests: fix performance tests

.github/actions/build-manager-image/action.yaml, .github/actions/e2e-test-gardener/action.yaml, .github/actions/e2e-test-k3d/action.yaml, .github/actions/integration-test/action.yaml, .github/actions/k8s-compatibility-test-aws/action.yaml, .github/actions/k8s-compatibility-test/action.yaml, .github/actions/upgrade-integration-test/action.yaml, .github/workflows/call-integration-tests.yaml, .github/workflows/call-pull-e2e.yaml, .github/workflows/post-main-workflow.yaml, .github/workflows/pull-build-push.yaml, .github/workflows/pull-request.yaml, .github/workflows/release-istio-2.yaml, Dockerfile, docs/release-notes/1.21.0.md, internal/reconciliations/istioresources/peer_authentication_mtls_test.go, internal/reconciliations/istioresources/proxy_protocol_envoy_filter_test.go, internal/resources/disclaimer_annotation_test.go, internal/resources/resources.go, internal/resources/resources_test.go, internal/resources/test_files/resource_after_labels.yaml, internal/resources/test_files/resource_before_labels.yaml, tests/integration/features/installation-suite/install.feature, tests/integration/scenario.go, tests/integration/steps/resource.go, tests/integration/testsupport/environments.go
- Fix labels reconciliation in resource manager - now it appends new labels if we introduce them in yaml definitions
- Fix `app.kubernetes.io/version` label which was broken due to build system issue - go build empty `-tags` argument caused `-ldflas` flag being treated as the argument for `-tags`
- introduced regression e2e test for `app.kubernetes.io/version` label
#1523
=> bug: Fix labels reconciliation in resource manager

docs/contributor/adr/0011-extend-external-authorizer-path-timeout.md
- Created ADR describing IstioCR's spec.config.[]authorizers extension with pathPrefix and timeout
refs:
- https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationHttpProvider-timeout
- https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-EnvoyExternalAuthorizationHttpProvider-path_prefix
related issues:
#1562
=> ADR: extend IstioCR authorizers with pathPrefix and timeout options
